### ISSUE TITLE
Build error fix Windows 7 env

### ISSUE THREAD

**Issue by johlim** [sixo/native-camera#1]
OS Windows 7
Android 3.2.1 
API 27 Level
NDK 16b

build fails reason : int_32_t type error 

**NdkCamerametadata.h** 

**before** 
#include <sys/cdefs.h>

#include "NdkCameraError.h"
#include "NdkCameraMetadataTags.h"

**after** 
#include <sys/cdefs.h>
#include <stdint.h>
#include "NdkCameraError.h"
#include "NdkCameraMetadataTags.h"

insert stdint.h below <sys/cdefs.h>

**Comment by sixo** [comment]
Currently I'm using NDK r18b and everything builds without errors. 
I checked **NdkCameraMetadata.h**  and I see that it already includes **<stdint.h>**. NdkCameraMetadata.h is of course part of the NDK (it's not part of the app itself), so there's no point to make changes there.
But sure, I could go through files in this project that use exact-width integer types and add the header to make them more self-sufficient.

Thanks for reporting this

**Comment by johlim** [comment]
thanks your feedback.
